name: Build All OnePlus Kernels
on:
  workflow_dispatch:
    inputs:
      FILE:
        type: choice
        description: "配置文件"
        required: true
        default: oneplus_ace2_pro_b
        options:
          - oneplus_nord_n30_se_5g_v
          - oneplus_10r_v
          - oneplus_nord_3_v
          - oneplus_ace_v
          - oneplus_ace_race_v
          - oneplus_10_pro_b
          - oneplus_10t_v
          - oneplus_11r_b
          - oneplus_ace2_b
          - oneplus_pad_lite_b
          - oneplus_pad_mt6983_b
          - oneplus_ace_2v_b
          - oneplus_ace_pro_v
          - oneplus_11_b
          - oneplus_12r_b
          - oneplus_ace2_pro_b
          - oneplus_ace3_b
          - oneplus_open_b
          - oneplus_nord_ce4_b
          - oneplus_12_b
          - oneplus_pad_go_2_b
          - oneplus_nord_ce4_lite_5g_b
          - oneplus_turbo_6v
          - oneplus_nord_4_b
          - oneplus_ace_3v_b
          - oneplus_pad_mt6897_b
          - oneplus_13r_b
          - oneplus_ace3_pro_b
          - oneplus_ace5_b
          - oneplus_pad_pro_b
          - oneplus_pad2_b
          - oneplus_nord_ce5_b
          - oneplus_nord_5_b
          - oneplus_ace5_pro_b
          - oneplus_13_b
          - oneplus_13t_b
          - oneplus_13s_b
          - oneplus_pad_2_pro_b
          - oneplus_pad_3_b
          - oneplus_ace5_race_b
          - oneplus_ace5_ultra_b
          - oneplus_ace5_ultra_bak_b
          - oneplus_pad2_mt6991_b
          - oneplus_ace_6
          - oneplus_turbo_6
          - oneplus_ace_6t
          - oneplus_ace_6t_aosp
          - oneplus_15r
          - oneplus_15r_aosp
          - oneplus_15
          - oneplus_15_aosp
          - oneplus_15t
          - oneplus_15t_aosp
      MANAGER_SOURCE:
        type: choice
        description: "管理器调用方向"
        required: true
        default: MD3
        options:
          - MD3
          - MD3_SPOOF
      SUSFS_CI:
        type: choice
        description: "SUSFS模块下载调用方向"
        required: true
        default: N/A
        options:
          - CI
          - Release
          - N/A
      KPM:
        type: choice
        description: "内核模块实现方式"
        required: true
        default: KPM
        options:
          - KPM
          - KPN
          - N/A
      SUSFS_META:
        type: string
        description: "回退SUSFS(输入哈希或次数或-1关闭)"
        required: false
        default: ""
      DYNAMIC_REPO:
        type: string
        description: "动态清单仓库所有者"
        required: true
        default: "Numbersf"
      BUILD_TIME:
        type: string
        description: "自定义构建时间(输入F使用UTCT或-1关闭)"
        required: false
        default: "Fri Dec 12 11:37:03 UTC 2025"
      KSU_META:
        type: string
        description: "分支名(必填)/自定义版本标识(留空不修改)/回退分支提交哈希版本(留空不修改)"
        required: false
        default: "main/Numbersf/"
      LZ4_UPDATE:
        type: boolean
        description: "(危险)是否升级LZ4到上游最新？"
        required: true
        default: false
      ZRAM:
        type: string
        description: "ZRAM(0关闭1开启)/算法名/大小"
        required: true
        default: "0/lz4kd/8589934592"
      SUFFIX:
        type: string
        description: "自定义内核后缀(不输入使用RAND_STR或-1关闭)"
        required: false
        default: ""
      SUBLEVEL:
        description: "自定义内核等级欺骗(SUBLEVEL)"
        required: false
        default: ""
      FAST_BUILD:
        type: boolean
        description: "是否启用极速构建？"
        required: true
        default: true
      LSM_BBG:
        type: boolean
        description: "是否启用关键分区写入保护模块(BBG)？"
        required: true
        default: true
      NETFILTER:
        type: boolean
        description: "是否启用网络功能拓展(NETFILTER)？"
        required: true
        default: true
      CCM:
        type: boolean
        description: "是否启用网络拥塞控制与管理机制(BBR+ECN)？"
        required: true
        default: true
      UNICODE_BYPASS:
        type: boolean
        description: "是否添加Unicode不可见字码点绕过读取漏洞修复？"
        required: true
        default: false
      SCHED_HMBIRD:
        type: boolean
        description: "是否添加风驰驱动1.0？"
        required: true
        default: false
      DROID_SPACES:
        type: boolean
        description: "是否添加轻量级Linux容器支持(DroidSpaces)？"
        required: true
        default: false
      RE_KERNEL:
        type: boolean
        description: "是否添加Re-Kernel？"
        required: true
        default: false
      SUSFS_DEV:
        type: boolean
        description: "是否拉取SUSFS-DEV分支？"
        required: true
        default: false
      SPACE_NOCLEAN:
        type: boolean
        description: "是否停用空间清扫？"
        required: true
        default: false
      BUILD_NOCCACHE:
        type: boolean
        description: "是否停用此次Ccache？"
        required: true
        default: false

jobs:
  build:
    name: ${{ github.event.inputs.FAST_BUILD == 'true' && ' [FAST]' || '' }}${{ contains(github.event.inputs.FILE, '_aosp') && ' [AOSP]' || '' }}${{ github.event.inputs.KPM == 'KPM' && ' [KPM]' || github.event.inputs.KPM == 'KPN' && ' [KPN]' || '' }}${{ github.event.inputs.LSM_BBG == 'true' && ' [BBG]' || '' }}${{ github.event.inputs.SCHED_HMBIRD == 'true' && ' [HMBIRD]' || '' }}${{ github.event.inputs.DROID_SPACES == 'true' && ' [DS]' || '' }}${{ startsWith(github.event.inputs.ZRAM, '1/') && ' [ZRAM]' || '' }}${{ github.event.inputs.RE_KERNEL == 'true' && ' [REKER]' || '' }}For ${{ github.event.inputs.FILE }} ${{ github.event.inputs.SUFFIX }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "none"
      CCACHE_NOHASHDIR: "true"
      CCACHE_NOHARDLINK: "true"
      CCACHE_IS_KERNEL_COMPILING: "true"
      CCACHE_MAXSIZE: 5G
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Maximize Build Space
        if: ${{ github.event.inputs.SPACE_NOCLEAN == 'false' }}
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'

      - name: Extract Manifest Info
        id: extract_info
        env:
          FILE: ${{ github.event.inputs.FILE }}
        run: |
          set -e
          cd "$GITHUB_WORKSPACE"
          if [[ "$FILE" =~ ^(.+)_([a-zA-Z])$ ]]; then
            FILE_CONF="${BASH_REMATCH[1]}"
          else
            FILE_CONF="$FILE"
          fi
          FILE_BASE=$(echo "$FILE_CONF" | sed -E 's/_bak//g; /_aosp/{s/_aosp//g;s/$/(AOSP)/;}; s/_([a-zA-Z0-9])/\U\1/g; s/^oneplus/OnePlus/; s/^realme/RealME/; s/^oppo/OPPO/')
          mkdir -p ".repo/manifests_fallback"
          XML_PATH=".repo/manifests_fallback/${FILE}.xml"
          README_PATH=".repo/manifests_fallback/README.md"
          echo "处理 FILE=$FILE, CONF=$FILE_CONF, BASE=$FILE_BASE"
          echo "FILE_CONF=$FILE_CONF" >> $GITHUB_ENV
          echo "FILE_BASE=$FILE_BASE" >> $GITHUB_ENV

          # 动态调用源码清单仓库，仓库优先级：1️⃣ OnePlusOSS → 2️⃣ Dynamic → 3️⃣ Appendix
          DYNAMIC_REPO_INPUT="${{
